apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-stretch-wordpress-prd-app
   annotations:
    hitachi.io/note: "pvc-stretch-wordpress-prd-app"
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 20Gi
   storageClassName: sc-gold-stretched
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-stretch-wordpress-prd-mysql
   annotations:
    hitachi.io/note: "pvc-stretch-wordpress-prd-mysql"
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 20Gi
   storageClassName: sc-gold-stretched
